### ISSUE TITLE
IM01 and IM01_hDyn

### ISSUE THREAD

**Issue by Light--** [tsenst/CrowdFlow#5]
excuse me, what's the meaning and difference between IM01 and IM01_hDyn ? 
What's the "_hDyn" stands for (was that stands for dynamic? then what does the "_h" mean ) ?
 ...and so on. Could u pls. share more description info. of the dataset ?

**Comment by tsenst** [comment]
IM01 are the sequences rendered with static camera setup und "_hDyn" with moving camera. Everything else in these sibling sequences is the same. "_h" has no additional special meaning. It was introduced by Gregory since at first we planned to release two kind of dynamical sequences ("_h" stood for highly dynamical).
